"""adding another models

Revision ID: 1ca8bd8b2ea2
Revises: 1032fff12aca
Create Date: 2025-09-29 12:11:24.099498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca8bd8b2ea2'
down_revision: Union[str, None] = '1032fff12aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('is_corrected', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_id'), 'sentences', ['id'], unique=False)
    op.create_index(op.f('ix_sentences_text'), 'sentences', ['text'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_index', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('lemma', sa.String(), nullable=True),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('xpos', sa.String(), nullable=True),
    sa.Column('feats', sa.JSON(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_form'), 'tokens', ['form'], unique=False)
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_token_index'), 'tokens', ['token_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_token_index'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_form'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_sentences_text'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_id'), table_name='sentences')
    op.drop_table('sentences')
    # ### end Alembic commands ###
